// Declaring the dependencies and variables
const fs = require("fs");
const inquirer = require("inquirer");

// questions prompts
inquirer
  .prompt([
    {
      type: "input",
      message: "What is your Project Name/Title?",
      name: "title"
    },
    {
      type: "editor",
      message: "Briefly Describe your project?",
      name: "description"
    },
    {
      type: "input",
      message: "Enter the link for your Github repository of the Project.",
      name: "link"
    },
    {
      type: "editor",
      message: "What are the steps required to install your project? Provide a step-by-step description of how to get the development environment running.",
      name: "installation"
    },
    {
      type: "editor",
      message: "Provide instructions and examples for use. Include screenshots as needed.",
      name: "usage"
    },
    {
      type: "editor",
      message: "List your collaborators, if any, with links to their GitHub profiles.",
      name: "credits"
    },
    {
      type: "list",
      message: "Choose an applicable license from the list",
      name: "license",
      choices: [
          "MIT License",
          "Apache License 2.0",
          "Mozilla Public License 2.0"
      ]
    },
    {
      type: "editor",
      message: "If you want other developers to contribute, Please add the guidelines to do so.",
      name: "contributing"
    },
    {
      type: "editor",
      message: "Go the extra mile and write tests for your application.",
      name: "tests"
    },
    {
      type: "input",
      message: "What is your Github Username?",
      name: "github"
    },
    {
      type: "input",
      message: "What is your email address?",
      name: "email"
    },
  ])
  .then(function(response) {


  var licenseUrl 
  var imageUrl

  if (response.license ==="MIT License"){
    licenseUrl = "https://opensource.org/licenses/MIT"
    imageUrl = "MIT-Green"
  } else if (response.license ==="Apache License 2.0"){
    licenseUrl = "https://www.apache.org/licenses/LICENSE-2.0"
    imageUrl = "Apache-BrightGreen"
  } else if (response.license ==="Mozilla Public License 2.0"){
    licenseUrl = "https://www.mozilla.org/en-US/MPL/2.0/"
    imageUrl = "Mozilla-Red"
  }


  // // generate Readme function populating the finalReadMe.md
  
  const finalReadMe = `
  # ${response.title}

  ![Badge](https://img.shields.io/badge/license-${imageUrl})
---

  ## Description
  ${response.description}
  [The Link to My Github Repository](${response.link})
---

  ## Table of Contents
  1. [Installation](#Installation)
  1. [Usage](#Usage)
  1. [Credits](#Credits)
  1. [License](#License)
---

  ## Installation
  ${response.installation}
---

  ## Usage
  ${response.usage}
---

  ## Credits
  ${response.credits}
---

  ## License
  #### This application is licensed under the [${response.license}](${licenseUrl})
  
---

  ## Collaborators
  ${response.contributing}
  
---

  ## Test
  ${response.tests}

---

  ## Questions
  #### You can reach me via my [Github](https://github.com/${response.github}) account. 
  #### Email me with any additional questions at: ${response.email}  
 
---
  ### This Readme was generated by [good-README-generator](https://github.com/kaurshalpreet/good-README-generator)


`


fs.writeFile("goodReadMe.md", finalReadMe, function(err) {

    if (err) {
      return console.log(err);
    }
  
    console.log("Success!");
  
  });

});
